### PR TITLE
Fix LinearMemory.current update bug

### PR DESCRIPTION
**Pull request by appcypher**
### What does this PR do?
- Fix a bug that has to do with updating `current` field of LinearMemory right after resizing it.

### How should this be manually tested?
- Run `make spectests && make test`.

### Background context
N/A

### Areas needing improvement
N/A

### CODE REVIEW

**Comment by syrusakbary** [comment]
Tests were passing before the bug, it seems we need a new test case for covering the scenario that this PR is solving so we don't repeat the issue again in the future

**Comment by syrusakbary** [comment]
@appcypher might be useful to add a custom spectests with that (kind of `custom_memory_grow.wast`), this way we also can have the pattern of `custom_XXX.wast` modules are just used within wasmer and not part of the spec itself

**Comment by appcypher** [comment]
Just realized we don't even have a `memory_grow.wast` test which should contain such case.
I will add that now

**Comment by syrusakbary** [comment]
LGTM!

**Pull request merged**
